Omniture settings and configurations
EdisonLabs/adobe_analytics pull request #1
Opened 2018-09-11 14:28 UTC by prash-ittb

Added option for CDN
- Amazon S3
- Tag manager

Added Data layer tab to build the the data layer JSON object

2018-09-13 11:32 UTC, timmillwood requested changes
I haven't manually tested but found a few nitpicks we should address before making publicly available.

2018-09-13 11:32 UTC, timmillwood commented on src/AdobeAnalyticsHelper.php
> +
Empty line not needed

2018-09-13 11:32 UTC, timmillwood commented on src/AdobeAnalyticsHelper.php
> +
Empty line not needed.

2018-09-13 11:32 UTC, timmillwood commented on src/AdobeAnalyticsHelper.php
> +      // Then admin settings with codesnippet first and finally taxonomy->vars.
Each line doesn't need a capital letter. Make sure each line is as close to (but no more than) 80 characters.

2018-09-13 11:32 UTC, timmillwood commented on src/AdobeAnalyticsHelper.php
> +
Empty line not needed.

2018-09-13 11:32 UTC, timmillwood commented on src/AdobeAnalyticsHelper.php
> +  protected function renderCdnMarkup($build) {
Docblock missing method parameter.

2018-09-13 11:32 UTC, timmillwood commented on src/AdobeAnalyticsHelper.php
> +  protected function renderDatalayerMarkup($build) {
Docblock missing parameter.

2018-09-13 11:32 UTC, timmillwood commented on src/AdobeAnalyticsHelper.php
> +  public function skipTracking($type) {
Docblock missing parameter and return value.

2018-09-21 10:13 UTC, suzymasri requested changes
Requesting minor modifications after manually testing the changes.

2018-09-21 10:13 UTC, suzymasri commented on src/Form/AdobeAnalyticsAdminSettings.php
> +      '#default_value' => $config->get('mode') ? $config->get('mode') : 'cdn',
The default value should be set to ```general``` instead of ```cdn```.

2018-09-21 10:13 UTC, suzymasri commented on src/Form/DataLayerForm.php
> +      '#default_value' => $config->get('omniture_track_roles'),
```track_roles``` config should be used instead. This part should be unified in all forms, both general & Data Layer forms.

2018-09-21 10:13 UTC, suzymasri commented on src/Form/DataLayerForm.php
> +<?php
The form is generating the following warning:
` Warning: Invalid argument supplied for foreach() in Drupal\Core\Render\Element\Checkboxes::valueCallback() (line 100 of /../../../../../../app/core/lib/Drupal/Core/Render/Element/Checkboxes.php)`

2018-09-21 13:34 UTC, matthewmyskowski-ittblazers requested changes

2018-09-21 13:34 UTC, matthewmyskowski-ittblazers commented on src/Form/AdobeAnalyticsAdminSettings.php
> +      '#title' => $this->t('Omniture S code Configuration Path'),
The word omniture is no longer used by Adobe. Here `Omniture` should be replaced with `Adobe Analytics`. All occurrences of this should be changed in the codebase.

2018-09-21 14:11 UTC, matthewmyskowski-ittblazers requested changes
Please add some basic tests to the module:
* can user with the analytics role/permissions access each config form
* can each form be submitted
* are values present after submission

2018-09-28 12:55 UTC, kmoll commented
Merging this so UI testing can continue.  Existing issues will continue to be addressed in a new PR

2018-09-28 12:55 UTC, merged